baseURL = "https://bangbangde.com/"
languageCode = "zh_CN"
title = "技术闲谈"
theme = "hugo-nuo"

enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
#disqusShortname = "blog.thor.today/disqus/xxx"
# Google Analytics UA number
#googleAnalytics = "UA-XXXXXXXX-X"

# Copyright of your post
copyright = "© 2018 - 技术闲谈  Powerd by Hugo & nuo-theme"

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"


[[menu.main]]
  name = "作品"
  weight = 90
  identifier = "works"
  url = "https://github.com/liufuqiang"

[[menu.main]]
  name = "标签"
  weight = 40
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "刘付强"
  avatar = "/img/avatar.jpg"
  seotitle = "Web开发方向的各种技术闲谈l"
  subtitle = "积沙成塔，集腋成裘"
  description = "这里不扯无聊话题，仅用于技术积累、学习心得只用。本博客涉及技术以服务端为主，但也涵盖其他领域的知识，涉及如： Go Golang Nginx Openresty PHP C C++ Vuejs Javascript Docker kubernetes."
  paginate = 10
  # Choose your social networks
  email = "liufuqiang0123@gmail.com"
  github = "liufuqiang"
  twitter = "fuqiangliu"
  #linkedin = "linkedin_username"
  weibo = "fuqiangliu"
  wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"
  # Changyan Comments (China Only)
  changyan = true
  changyanId = "cytM9xuce"
  changyanConf = "prod_b985ef3db2e98b59b3ff3aacc6c1aa5d"
  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"
  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  msValidate = "22596E34341DD1D17D6022C44647E587"
  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  # baiduTongji = "e21dc1e8a592188271b615159dc88af7"

  # ICP Number (China Only)
  ICP = "冀ICP备18027023号"
